@baseUrl = http://localhost:3000/auth
 ####
POST {{baseUrl}}/login
 Content-Type: application/json 

 {
    "username":"admin",
    "password":"admin"
 }  
###
POST {{baseUrl}}/login
 Content-Type: application/json 

 {
    "username":"user1",
    "password":"null007"
 }  

###
POST {{baseUrl}}/register
 Content-Type: application/json 

 {
    "username":"userTest",
    "name":"Test",
    "firstname":"User",
    "mail":"UserTest@mail.com",
    "yearBithday":"2002",
    "password":"test"
 }  

###
GET {{baseUrl}}/logout

